.TH VGD 1 "5 March 2005"
.SH NAME
vgd \- Viewglob daemon.
.SH SYNOPSIS
.B vgd
.RI [ options ]

.SH DESCRIPTION
\fIvgd\fP acts as a mediator between any number of \fIvgseer\fP processes and a single Viewglob display process.  It keeps track of the active terminal and passes information from the corresponding vgseer (if there is one) to the display.
.PP
While vgseer can be used on a remote machine using ssh or telnet, vgd is only useful if it's running on the same X server as the user (meaning, in most cases, locally).
.PP

.SH OPTIONS
This program follows the usual GNU command line syntax, with long options starting with two dashes.  A summary is included below.
.TP
.B \-p, \-\-port=<number>
Listen on the given port.  The default is 16108 (1-GLOB).
.TP
.B \-d, \-\-display=<vgclassic|vgmini|[path]>
Display program.  The Viewglob package comes with \fIvgclassic\fP and \fIvgmini\fP (the new display).  Though there aren't any other displays in existence at this point, one could be used instead by passings its path.  The default is vgmini.
.TP
.B \-\-persistent
Keep vgd around even after all vgseers have disconnected.  It will sit and listen for new connections.
.TP
.B \-f, \-\-config\-file=path
Use an alternate config file (\fI~/.viewglobrc\fP is the default). FIXME
.TP
.B \-z, \-\-font\-size\-modifier=<+/\-##>
Increase or decrease the base font size in the display by the given number.  E.g. "\-z +2" increases the window manager's default by 2, while "\-z \-2" decreases the default by 2.
.TP
.B \-b, \-\-disable\-icons
Don't show file type icons in the display, just names.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show the version of the program.

