.TH VGSEER 1 "5 March 2005"
.SH NAME
vgseer \- Viewglob shell overseer.
.SH SYNOPSIS
.B vgseer
.RI [ options ]

.SH DESCRIPTION
\fIvgseer\fP creates a Viewglob-supervised interactive shell and opens up an Internet-domain socket connection to a listening \fIvgd\fP process.  It maintains a snapshot of the relevant parts of its local filesystem and tracks the user's command line and other information, which it communicates to vgd.
.PP
\fIvgseer\fP is compatible with any recent version of \fIbash\fP or \fIzsh\fP and doesn't assume any particular shell configuration.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long options starting with two dashes.  A summary is included below.
.TP
.B \-h, \-\-host=<name>
Connect to a vgd process on the given host.  The default is 127.0.0.1 (localhost).
.TP
.B \-p, \-\-port=<number>
Connect to a vgd process through the given port.  The default is 16108 (1-GLOB).
.TP
.B \-c, \-\-shell\-mode=<name>
Shell to be used.  \fIname\fP can be "bash" or "zsh" (default is bash).
.TP
.B \-f, \-\-config\-file=<path>
Use an alternate config file (\fI~/.viewglobrc\fP is the default).  FIXME
.TP
.B \-s, \-\-sort\-style=<windows|ls>
In the display, sort files with directories first (Windows) or purely by name (ls).  ls mode is the default.
.TP
.B \-r, \-\-dir\-order=<descending|ascending|ascending\-pwd\-first>
In the display, list directories in descending order (the default), ascending (last referenced directory has the top listing), or ascending with the current directory always first.
.TP
.B \-t, \-\-disable\-star
Disable the asterisk character which is usually at the beginning of a vgseer shell prompt.
.TP
.B \-e, \-\-executable=<path>
Use the given executable as the shell instead of its first reference in the path.  Note that if this isn't a version of the shell chosen with \-\-shell\-mode, you won't get very far.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show the version of the program.

